; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:uno]
; platform = atmelavr
; board = uno
; framework = arduino
; monitor_speed = 9600
; monitor_eol = LF
; lib_deps =
;   chris--a/Keypad
;   marcoschwartz/LiquidCrystal_I2C
; src_filter = +<*> -<lab_2_2/>

[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 9600
monitor_eol = LF
build_flags = -DLAB_2_2
lib_deps =
  feilipu/FreeRTOS
build_src_filter = +<*> -<lab_2_1/> -<lab_1_1/> -<lab_1_2/> -<srv_os_sequential/> -<dd_keypad/> -<dd_lcd/> -<srv_lcd_keypad_stdio/>

